# -*- coding: utf-8 -*-
"""FIB302.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aBOAhVlQwWR3E19CJUtv-HnlpWgdJMNO

# Lista Python 1

1 - Defina três variáveis: um inteiro, um número de ponto flutuante e uma string. Imprima o tipo de cada variável.
"""

# Definindo as variáveis
numero_inteiro = 7
numero_float = 16.5
texto_string = "Olá, Python"

# Imprimindo
print(type(numero_inteiro)) # <class 'int'>
print(type(numero_float))   # <class 'float'>
print(type(texto_string))   # <class 'str'>

"""2 - Execute as seguintes operações e imprima os resultados:"""

# Operações
soma = 5 + 3
divisao = 15.5 / 3.2
concatenacao = "Data" + "Science"

print(f"Soma de inteiros: {soma}")
print(f"Divisão de floats: {divisao}")
print(f"Concatenação: {concatenacao}")

# Entrada e Saída
nome = input("Por favor, insira seu nome: ")
print(f"Seja muito bem-vinde, {nome}!")

"""3 - Escreva um programa que calcule a área de um retângulo. Solicite ao usuário o comprimento e a largura e imprima o resultado.

"""

print("* Cálculo da Área de um Retângulo *")
comprimento = float(input("Digite o comprimento: "))
largura = float(input("Digite a largura: "))

area = comprimento * largura

print(f"A área do retângulo é: {area}")

"""4 - Peça ao usuário uma temperatura em Celsius e converta para Fahrenheit. Imprima o resultado.

"""

print("* Conversor de graus Celsius para Fahrenheit *")
celsius = float(input("Digite a temperatura em Celsius: "))

fahrenheit = (celsius * 1.8) + 32

print(f"A temperatura em Fahrenheit é: {fahrenheit:.1f}°F")

"""5 - Escreva um programa que calcule o valor da expressão: (2 * (3 + 4)) / 5. Imprima o resultado."""

resultado = (2 * (3 + 4)) / 5
print(f"(2 * (3 + 4)) / 5 = {resultado}")
# O cálculo é: (2 * 7) / 5 -> 14 / 5 -> 2.8

"""6 - Crie uma string e imprima-a na ordem inversa."""

minha_string = "Pássaro"
string_invertida = minha_string[::-1]

print(f"Original: {minha_string}")
print(f"Invertida: {string_invertida}")

"""7 - Crie uma string com uma mistura de letras maiúsculas e minúsculas. Converta para letras maiúsculas e imprima o resultado."""

texto_misto = "MAÍuscULo E miNÚsCulO"
texto_maiusculo = texto_misto.upper()

print(f"Resultado: {texto_maiusculo}")

"""1 - Suponha que a posição de um ponto no espaço bidimensional é dado em coordenadas polares r, θ queremos convertê-lo em coordenadas cartesianas x , y. Escreva um programa para fazer essa conversão."""

import math

print("* Conversor de Coordenadas Polares para Cartesianas *")
r = float(input("Digite o valor do raio (r): "))
theta_graus = float(input("Digite o ângulo (theta) em graus: "))

# Conversão de graus para radianos
theta_rad = math.radians(theta_graus)

# Fórmulas: x = r * cos(theta), y = r * sin(theta)
x = r * math.cos(theta_rad)
y = r * math.sin(theta_rad)

print(f"\nResultados:")
print(f"Coordenada x: {x:.4f}")
print(f"Coordenada y: {y:.4f}")

"""2 - Escreva um programa que compute os principais parametros de um lançamento obliquo dado o módulo da velocidade inicial e o angulo de lançamento. Imprima a saída de maneira que os resultados sejam descritos claramente."""

import math

print("* Calculadora de Lançamento Oblíquo *")
v0 = float(input("Velocidade inicial (m/s): "))
angulo_graus = float(input("Ângulo de lançamento (graus): "))
g = 9.8  # Aceleração da gravidade

# Convertendo para radianos
theta = math.radians(angulo_graus)

# Tempo total de voo: T = 2 * v0 * sin(theta) / g
tempo_total = (2 * v0 * math.sin(theta)) / g

# Altura máxima: H = (v0^2 * sin^2(theta)) / 2g
altura_max = (v0**2 * math.sin(theta)**2) / (2 * g)

# Alcance horizontal: R = (v0^2 * sin(2*theta)) / g
alcance = (v0**2 * math.sin(2 * theta)) / g

print("\n* Parâmetros do Movimento *")
print(f"Tempo total de voo: {tempo_total:.2f} s")
print(f"Altura máxima:      {altura_max:.2f} m")
print(f"Distância (horizontal) percorrida: {alcance:.2f} m")

"""3 - Escreva um programa que cheque se um numero dado é par ou impar."""

numero = int(input("Digite um número inteiro: "))

if numero % 2 == 0:
    print(f"O número {numero} é PAR.")
else:
    print(f"O número {numero} é ÍMPAR.")

"""# Lista Python 2

1. Defina uma lista contendo cinco inteiros. Imprima a lista inteira e o terceiro elemento.
"""

# Definição e Acesso
lista_inteiros = [10, 20, 30, 40, 50]
print(f"Lista completa: {lista_inteiros}")
print(f"Terceiro elemento (índice 2): {lista_inteiros[2]}")

"""2. Crie uma lista vazia e anexe três inteiros a ela. Em seguida, estenda a lista com outra lista contendo mais dois inteiros. Imprima a lista final."""

# Append e Extend
lista_vazia = []
# Anexando um por um
lista_vazia.append(1)
lista_vazia.append(2)
lista_vazia.append(3)
# Estendendo com outra lista
lista_vazia.extend([4, 5])
print(f"Lista final: {lista_vazia}")

"""3. Defina uma lista de 10 números. Imprima os primeiros cinco números e os últimos cinco números usando fatiamento."""

# Fatiamento (Slicing)
numeros = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(f"Primeiros cinco: {numeros[:5]}")
print(f"Últimos cinco: {numeros[-5:]}")

"""4. Crie duas listas de igual comprimento contendo inteiros. Adicione os elementos correspondentes das duas listas e imprima o resultado (Obs: sem usar FOR)."""

# Soma elemento a elemento (Sem 'for' explícito)
# Listas nativas não somam matematicamente com '+'.
# Usamos list comprehension com zip (ou map)
lista_a = [1, 2, 3]
lista_b = [4, 5, 6]
soma_elementos = [x + y for x, y in zip(lista_a, lista_b)]
print(f"Soma elemento a elemento: {soma_elementos}")

"""5. Defina duas listas e concatene-as sem usar o operador `+`. Imprima a lista concatenada.

"""

# Concatenação sem operador '+'
# Podemos usar o desempacotamento (unpacking) ou o método extend
l1 = [1, 2]
l2 = [3, 4]
lista_concatenada = [*l1, *l2] # Método moderno e elegante
print(f"Lista concatenada: {lista_concatenada}")

"""6. Crie um array de inteiros. Imprima o array.

"""

import numpy as np

# Criando um Array de inteiros
array_int = np.array([1, 2, 3, 4, 5])
print(f"Array Numpy: {array_int}")

"""7. Crie um array de números de ponto flutuante. Acesse o terceiro elemento e modifique-o. Imprima o array modificado."""

import numpy as np

# Array de ponto flutuante e modificação
array_float = np.array([1.5, 2.5, 3.5, 4.5])
# Acessando o 3º elemento (índice 2)
print(f"Elemento original: {array_float[2]}")
array_float[2] = 99.9 # Modificação
print(f"Array modificado: {array_float}")

"""8. Defina dois arrays de inteiros usando a biblioteca numpy. Adicione os elementos correspondentes e imprima o resultado.

"""

import numpy as np

# Soma vetorial com Numpy
# Diferente das listas (exercício 4), arrays somam diretamente
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])
soma_arrays = arr1 + arr2
print(f"Soma direta de arrays: {soma_arrays}")

"""9. Defina arrays para velocidade inicial, ângulo e tempo. Calcule e imprima as posições horizontal e vertical de um projétil usando as equações de movimento pertinentes. Suponha que v_0 = 20m/s, theta = 45 graus e g = 9,8m/s2."""

# Movimento de Projétil
# Parâmetros
v0 = 20.0       # m/s
theta = 45.0    # graus
g = 9.8         # m/s^2

# Convertendo ângulo para radianos
theta_rad = np.deg2rad(theta)

# Criando um array de tempo (de 0 a 3 segundos, com 10 pontos)
t = np.linspace(0, 3, 10)

# Equações de movimento
# x = v0 * cos(theta) * t
pos_x = v0 * np.cos(theta_rad) * t
# y = v0 * sin(theta) * t - 0.5 * g * t^2
pos_y = v0 * np.sin(theta_rad) * t - 0.5 * g * t**2

print("* Projétil *")
print(f"Tempos: {t}")
print(f"Posições X: {pos_x}")
print(f"Posições Y: {pos_y}")

"""10. Defina arrays para tempo e deslocamento. Calcule e represente graficamente o deslocamento de um objeto em movimento harmônico simples. Suponha que a amplitude seja A = 1m e  a velocidade angular omega = 2*pi rad/s."""

import matplotlib.pyplot as plt

# Movimento Harmônico Simples (MHS)
A = 1.0         # Amplitude (m)
omega = 2 * np.pi # Velocidade angular (rad/s)
t_mhs = np.linspace(0, 2, 100) # 2 segundos

# x(t) = A * cos(omega * t)
deslocamento = A * np.cos(omega * t_mhs)

# Gráfico
plt.figure(figsize=(8, 4))
plt.plot(t_mhs, deslocamento)
plt.title("Movimento Harmônico Simples")
plt.xlabel("Tempo (s)")
plt.ylabel("Deslocamento (m)")
plt.grid(True)
plt.show()

"""- Defina um array de 10 inteiros. Imprima sua forma e remodele-a em uma matriz 2x5. Imprima a matriz remodelada."""

# Reshape (Remodelar)
arr_10 = np.arange(10) # Cria array [0, 1, ..., 9]
print(f"Forma original: {arr_10.shape}")
matriz_2x5 = arr_10.reshape(2, 5)
print(f"Matriz 2x5:\n{matriz_2x5}")

"""- Defina um array de 10 inteiros. Escreva um programa que extraia e imprima apenas os números pares do array usando indexação booleana."""

# Indexação Booleana (Máscara)
# Extrair apenas pares
pares = arr_10[arr_10 % 2 == 0]
print(f"Apenas pares: {pares}")

"""- Escreva um programa que calcule o produto escalar de dois arrays de inteiros usando numpy. Imprima o resultado."""

# Produto Escalar (Dot Product)
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
# Produto escalar: (1*4) + (2*5) + (3*6) = 4 + 10 + 18 = 32
prod_escalar = np.dot(v1, v2)
# Alternativa moderna: v1 @ v2
print(f"Produto Escalar: {prod_escalar}")

"""- Crie uma matriz 2x3 usando numpy. Transponha a matriz e imprima a matriz transposta.

"""

# Transposta
matriz = np.array([[1, 2, 3],
                   [4, 5, 6]]) # Matriz 2x3
transposta = matriz.T          # Vira 3x2
print(f"Transposta:\n{transposta}")

"""# Lista Python 3

1 - Faça um programa para calcular a sequencia de Fibonacci até 1000.
"""

print("* Sequência de Fibonacci (até 1000) *")

# Termos iniciais
a, b = 0, 1

# Enquanto 'a' for menor ou igual a 1000, execute o bloco
while a <= 1000:
    print(a, end=' ') # O end=' ' imprime na mesma linha

    # Atualização das variáveis:
    # 'a' recebe o valor de 'b'
    # 'b' recebe a soma antiga (a + b)
    a, b = b, a + b

print() # Apenas para pular uma linha no final

"""2 - Usando o inicio de código abaixo, finalize o programa para encontrar o tempo em que o projetil passa de sua altura máxima:"""

from numpy import linspace

v0 = 4.5 # velocidade inicial
g = 9.81 # aceleração da gravidade
t = linspace(0, 1, 1000) # 1000 pontos do intervalo de tempo
y = v0*t - 0.5*g*t**2 # calcula todas as alturas do lançamento

# ache quando a bola passa de y=0

# Encontrar o índice (posição no array) onde y é máximo
indice_do_maximo = argmax(y)

# Usar esse índice para pegar o tempo correspondente no array t
tempo_max = t[indice_do_maximo]
altura_max = y[indice_do_maximo]

print(f"A altura máxima é atingida em t = {tempo_max:.4f} s")
print(f"A altura máxima é: {altura_max:.4f} m")

"""3 - Faça um programa que peça um numero ao usuário e identifique se o numero é par ou ímpar"""

print("* Verificador Par ou Ímpar *")
try:
    numero = int(input("Digite um número inteiro: "))

    if numero % 2 == 0:
        print(f"O número {numero} é PAR.")
    else:
        print(f"O número {numero} é ÍMPAR.")

except ValueError:
    print("Por favor, digite um número inteiro válido.")

"""1 - Faça um programa que calcule a somatória:"""

# Definindo o limite superior da somatória (N)
N = 100
soma_total = 0

print(f"Calculando a somatória para N = {N}")

for n in range(1, N + 1):
    termo = 1/n
    soma_total += termo

print(f"O resultado da somatória é: {soma_total}")

"""2 - Faça um programa que calcule as primeiras 5 linhas das 3 principais séries de linhas do Hidrogenio (m=1,2,3), Lyman, Balmer e Paschen de acordo com a fórmula de Rydberg"""

# Constante de Rydberg (em nm^-1)
R = 1.097e-2

# Séries
series_nomes = {
    1: "Lyman (UV)",
    2: "Balmer (Visível)",
    3: "Paschen (Infravermelho)"
}

print(f"{'Série':<20} | {'Transição (n->m)':<18} | {'Comp. de Onda (nm)':<20}")
print("=" * 65)

# Loop pelas séries m=1, m=2, m=3
for m in [1, 2, 3]:

    # Loop pelas 5 primeiras linhas de cada série
    # As linhas começam sempre em n = m + 1
    for k in range(1, 6):
        n = m + k

        # Fórmula de Rydberg: 1/lambda = R * (1/m² - 1/n²)
        um_sobre_lambda = R * ( (1/(m**2)) - (1/(n**2)) )

        # Invertendo para achar o lambda
        lambda_nm = 1 / um_sobre_lambda

        # Imprimindo formatado
        nome = series_nomes[m] if k == 1 else "" # Mostra o nome apenas na 1ª linha do bloco
        print(f"{nome:<20} | n={n} -> m={m}      | {lambda_nm:.2f} nm")

    print("-" * 65) # Separador entre séries

"""1 - Escreva um programa que peça um número ao usuário e imprima se ele é par ou ímpar."""

print("* Par ou Ímpar *")
num = int(input("Digite um número: "))
if num % 2 == 0:
    print(f"{num} é Par.")
else:
    print(f"{num} é Ímpar.")

"""2 - Escreva um programa que peça ao usuário uma nota (0-100) e imprima se for "Aprovado" (>=60) ou "Reprovado" (<60)."""

nota = float(input("Digite sua nota (0-100): "))

if nota >= 60:
    print("Status: Aprovado")
else:
    print("Status: Reprovado")

"""3 - Escreva um programa que gere um número aleatório entre 1 e 100. Peça ao usuário para adivinhar o número. Continue avisando o usuário até que ele adivinhe corretamente. Forneça feedback se a estimativa for muito alta ou muito baixa."""

import random

print("* Adivinhe o número (1 a 100) *")
numero_secreto = random.randint(1, 100)
palpite = 0
tentativas = 0

# O loop continua enquanto o palpite for diferente do segredo
while palpite != numero_secreto:
    try:
        palpite = int(input("Seu palpite: "))
        tentativas += 1

        if palpite < numero_secreto:
            print("Muito baixo! Tente um número maior.")
        elif palpite > numero_secreto:
            print("Muito alto! Tente um número menor.")
        else:
            print(f"Parabéns! Você acertou o número {numero_secreto} em {tentativas} tentativas.")

    except ValueError:
        print("Por favor, digite um número inteiro válido.")

"""4 - Escreva um programa que peça ao usuário um número inteiro positivo e calcule seu fatorial usando um loop while."""

print("* Cálculo de Fatorial *")
n = int(input("Digite um número inteiro positivo: "))
original_n = n

fatorial = 1

if n < 0:
    print("Fatorial não existe para números negativos.")
elif n == 0:
    print("O fatorial de 0 é 1")
else:
    while n > 0:
        fatorial *= n  # Multiplica o acumulador pelo n atual
        n -= 1         # Decrementa n

    print(f"O fatorial de {original_n} é: {fatorial}")

"""5 - Escreva um programa que peça uma string ao usuário e verifique se é um palíndromo."""

print("* Verificador de Palíndromo *")
texto = input("Digite uma palavra: ")

# Tratamento básico: remover espaços e deixar minúsculo para comparação justa
texto_limpo = texto.replace(" ", "").lower()

# Verifica se o texto é igual ao seu inverso
if texto_limpo == texto_limpo[::-1]:
    print("É um palíndromo!")
else:
    print("Não é um palíndromo.")

"""6 - Escreva um programa que peça um número ao usuário e verifique se é um número primo."""

num = int(input("Digite um número para verificar se é primo: "))

eh_primo = True

if num <= 1:
    eh_primo = False
else:
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            eh_primo = False
            break # Interrompe o loop imediatamente se encontrar um divisor

if eh_primo:
    print(f"{num} é um número PRIMO.")
else:
    print(f"{num} NÃO é primo.")